# WhatATheme
markdown: kramdown

# URL of the Site
url: 'https://sarahhoran.github.io'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: ""

# Title of the Site
title: Sarah Horan
# Description of the Site
description: MSU Computational Data Science | Aspiring Cybersecurity Leader
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Portfolio, Cybersecurity, Data Science, MSU
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: horansa3@msu.edu
facebook_username: ""
twitter_username: ""
instagram_username: ""
linkedin_username: sarahhoran
github_username:  sarahhoran
youtube_channel_id: UCk_93NXYP-U_AOB5GfWlOow
reddit_username: ""
behance_username: ""
dribbble_username: ""
spotify_username: ""

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: Sarah Horan
# URL for the Image of the Author
author-image: https://i.postimg.cc/y81DwZkR/Full-Size-Render-VSCO.jpg
# 60 Words About the Author
author-about: Third-year student at Michigan State studying Computational Data Science. Passionate about cybersecurity, machine learning, and making tech more human..
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/sarahhoran

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
